// Generated by IcedCoffeeScript 108.0.12
define(["Vue"], function (Vue) {
  return Vue.component("v-404", {
    template: "<p style='line-height: 20; text-align: center'><span style='color: red; font-size: 26px; margin-right: 50px;'>404 Not Found</span>你来到了未知的荒原。。。</p>",
    data: function () {
      return {};
    }
  });
});
