// Generated by IcedCoffeeScript 108.0.12
define(["Vue", "text!../../../views/home/index.html"], function(Vue, template) {
  return Vue.component("v-home", {
    template: template,
    data: function() {
      return {
        timeout: void 0,
        count: 0,
        lastTime: new Date().getTime(),
        during: 2000
      };
    },
    mounted: function() {
      return this.refresh();
    },
    methods: {
      refresh: function() {
        this.now = new Date();
        return setTimeout(this.refresh, 2000);
      },
      debounce: function() {
        if (!this.timeout) {
          return this.timeout = window.setTimeout((function(_this) {
            return function() {
              _this.count++;
              return console.log(_this.count);
            };
          })(this), 1000);
        } else {
          window.clearTimeout(this.timeout);
          return this.timeout = window.setTimeout((function(_this) {
            return function() {
              _this.count++;
              return console.log(_this.count);
            };
          })(this), 1000);
        }
      },
      throttleFun: function() {
        this.count++;
        return console.log(this.count);
      },
      throttle: function() {
        var now;
        now = new Date().getTime();
        if (now - this.lastTime > this.during) {
          this.throttleFun();
          return this.lastTime = now;
        }
      }
    }
  });
});
