// Generated by IcedCoffeeScript 108.0.12
define(["text!../../../views/mumianhua/index.html", "Vue", "./scene"], function(html, Vue, Scene) {
  return Vue.component("v-three", {
    template: html,
    data: (function(_this) {
      return function() {
        return {
          scene: null
        };
      };
    })(this),
    mounted: (function(_this) {
      return function() {
        return _this.scene = new Scene(document.getElementById("page-canvas"));
      };
    })(this),
    methods: {
      changeBtn: (function(_this) {
        return function() {
          return _this.scene.changeBtn();
        };
      })(this)
    }
  });
});
